# Docker Compose file for ROSCONES_25 BT.CPP tutorial
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To run a specific service by name:
#   docker compose run <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:
  dev-base:
    image: ${BUILT_IMAGE}
    init: true
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Allows graphical programs in the container.
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USERNAME=${USERNAME}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}  
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .vscode/:/roscon25_ws/.vscode/:rw
      - ../worlds/:/roscon25_ws/worlds/:rw
      - ../src/:/roscon25_ws/src/btdev/:rw
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    command:  bash -c "source /roscon25_ws/install/setup.bash && colcon build --symlink-install --event-handlers console_direct+; sleep infinity"